### ISSUE TITLE
Resulting QR code doesnt honor leading '0' in variable_symbol

### ISSUE THREAD

**Issue by Horkyze** [matusf/pay-by-square#1]
```
code = pay_by_square.generate(
  amount = 100,
  iban = 'SK7283300000009111111118',
  variable_symbol = '0909',
)
img = qrcode.make(code)
img.save('test.png')
```

**Expectation**
Resulting QR code after scan should contain VS as **0909** and not **909**

**Result**

![test](https://user-images.githubusercontent.com/1040383/92889293-6342c700-f416-11ea-8f35-f6dc8c0f5a63.png)

Loaded code in banking application:
![imag](https://user-images.githubusercontent.com/1040383/92889414-83728600-f416-11ea-84c3-ae6f4e21d263.png)

**Comment by matusf** [comment]
Hi, I scanned it with different banking app and the VS was not stripped. Maybe an issue with the banking app?
![photo_2020-09-17_19-48-31](https://user-images.githubusercontent.com/18228995/93508538-c785ef00-f91e-11ea-815b-5f20faf2887d.jpg)
